site:
  title: OpenTiny Documentation (Staging)
  url: https://staging.tiny.cloud/docs
  start_page: opentiny::index.adoc
content:
  sources:
  - url: ./
    branches: HEAD
    start_path: ./
urls:
  html_extension_style: indexify
ui:
  bundle:
    url: ./ui-bundle
asciidoc:
  attributes:
    tinymce_live_demo_url: https://cdn.tiny.cloud/1/qagffr3pkuv17a8on1afax661irst1hbr4e6tbv888sz91jc/tinymce/6-testing/tinymce.min.js
  extensions:
    - '@tinymce/antora-extension-livedemos'
