site:
  title: OpenTiny Documentation
  url: https://opentiny.mild.blue
  start_page: opentiny::index.adoc
content:
  sources:
  - url: ./
    branches: HEAD
    start_path: ./
urls:
  html_extension_style: indexify
ui:
  bundle:
    url: ./ui-bundle
asciidoc:
  extensions:
    - '@tinymce/antora-extension-livedemos'
